### ISSUE TITLE
trying to build linux from v1_0

### ISSUE THREAD

**Issue by suhasskrishanmurthy** [sifive/freedom-u-sdk#138]
I am trying to build linux to run on spike( it is reguired for project i am working), it is not building properly.

This is the part of build process where error came.

>>> libtirpc 1.0.1 Updating config.sub and config.guess
for file in config.guess config.sub; do for i in $(find /home/suhas/freedom-u-sdk/work/buildroot_initramfs/build/libtirpc-1.0.1 -name $file); do cp support/gnuconfig/$file $i; done; done
>>> libtirpc 1.0.1 Configuring
>>> libtirpc 1.0.1 Autoreconfiguring
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/\${ <-- HERE ([^ \t=:+{}]+)}/ at /home/suhas/freedom-u-sdk/work/buildroot_initramfs/host/usr/bin/automake line 3936.
autoreconf: /home/suhas/freedom-u-sdk/work/buildroot_initramfs/host/usr/bin/automake failed with exit status: 255
package/pkg-generic.mk:185: recipe for target '/home/suhas/freedom-u-sdk/work/buildroot_initramfs/build/libtirpc-1.0.1/.stamp_configured' failed
make[2]: *** [/home/suhas/freedom-u-sdk/work/buildroot_initramfs/build/libtirpc-1.0.1/.stamp_configured] Error 1
Makefile:36: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/suhas/freedom-u-sdk/buildroot'
Makefile:90: recipe for target '/home/suhas/freedom-u-sdk/work/buildroot_initramfs/images/rootfs.tar' failed
make: *** [/home/suhas/freedom-u-sdk/work/buildroot_initramfs/images/rootfs.tar] Error 2

I have enabled CONFIG_HVC_RISCV_SBI=y. 
Still its not building.
Please help.

**Comment by jim-wilson** [comment]
This is a versioning problem.  It looks like you are trying to build an old version of freedom-u-sdk on a new linux release.  You didn't specify which freedom-u-sdk you are building; I'm assuming the v1_0 branch.  This is known to build on Ubuntu 16.04.  It won't build on some newer operating systems without patches, because new versions of some tools like perl/python are rejecting code that old versions used to accept.  You can try patching the files that won't work with current linux versions.  Or you can try installing Ubuntu 16.04 on a machine, or a container or other vm environment, and do the freedom-u-sdk build there.  Some of the patches you need are already on branches, but they aren't used by default as they were added after the release.  If you do "cd buildroot; git log origin/sifive | more" you will see 3 patches added after the release that fix versioning problems, including the one you reported.  If you update the buildroot submodule it should build OK on at least Ubuntu 18.04.  I doubt that anyone has tried Ubuntu 20.04. After updating the buildroot tree, avoid doing a git submodule update at the toplevel as that will revert back to the old version of this submodule.

Another option is to try using an alternative github tree
    https://github.com/phantom-v/riscv-rss-sdk
which uses more recent versions of everything.  The v1_0 branch uses 2-3 year old versions of everything.
